# Generated by Django 4.2.2 on 2023-06-29 20:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Assignment Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('documentFiles', models.FileField(blank=True, null=True, upload_to='document/course/assignment', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt'])], verbose_name='Document')),
                ('status', models.BooleanField(default=False, verbose_name='Is Marked')),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('documentFiles', models.FileField(blank=True, null=True, upload_to='document/course/assignment/report', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt'])], verbose_name='Document')),
                ('status', models.BooleanField(default=False, verbose_name='Is Received')),
                ('createdDate', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.assignment', verbose_name='Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_name', models.CharField(max_length=100, unique=True, verbose_name='Cohort Name')),
                ('starting_date', models.DateField(verbose_name='When Start')),
                ('ending_date', models.DateField(verbose_name='When End')),
                ('status', models.BooleanField(default=False, verbose_name='Is Completed')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Company Name')),
                ('location', models.CharField(max_length=200, verbose_name='Location Address')),
                ('logoFile', models.ImageField(blank=True, null=True, upload_to='images/profile/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Logo Image')),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Stack Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Module Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('documentFiles', models.FileField(blank=True, null=True, upload_to='document/course', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt'])], verbose_name='Document')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.stack', verbose_name='Stack belonging')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.cohort', verbose_name='Cohort belonging')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.stack', verbose_name='Stack belonging')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100, unique=True, verbose_name='Assignment Grade')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='main.assignmentreport', verbose_name='Assignment Report')),
            ],
        ),
        migrations.CreateModel(
            name='Cohort_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(choices=[('', 'Select Schedule'), ('Application', 'Application'), ('Interview', 'Interview'), ('Graduation', 'Graduation')], default='', max_length=12, verbose_name='Schedule Name')),
                ('start_period', models.DateTimeField()),
                ('end_period', models.DateTimeField()),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.cohort', verbose_name='Cohort Scheduled')),
            ],
        ),
        migrations.AddField(
            model_name='assignmentreport',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.group', verbose_name='Submitting Group'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.cohort', verbose_name='Cohort belonging'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.stack', verbose_name='Stack belonging'),
        ),
    ]
