# Generated by Django 4.2.2 on 2023-07-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='grade',
            field=models.CharField(max_length=100, verbose_name='Assignment Grade'),
        ),
    ]
